import { AppLanguage } from '../../../../shared/config/languages.config';

export interface UserQueryTranslation {
  title: string;
  subtitle: string;
  addButton: string;

  stats: {
    total: string;
    active: string;
    pending: string;
  };

  filters: {
    searchLabel: string;
    searchPlaceholder: string;
    statusLabel: string;
    statusPlaceholder: string;
    allStatuses: string;
  };

  statuses: {
    active: string;
    inactive: string;
    pending: string;
  };

  table: {
    name: string;
    email: string;
    role: string;
    status: string;
    lastAccess: string;
    actions: string;
    loading: string;
    emptyTitle: string;
    emptyDescription: string;
    rowsPerPage: string;
    paginatorInfo: string;
    firstPage: string;
    previousPage: string;
    nextPage: string;
    lastPage: string;
  };

  actions: {
    view: string;
    edit: string;
  };

  dialog: {
    addTitle: string;
    addSubtitle: string;
    viewTitle: string;
    viewSubtitle: string;
    loadingView: string;
    close: string;
    closeButton: string;
    cancel: string;
    save: string;
    update: string;
  };

  form: {
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    phoneLabel: string;
    phonePlaceholder: string;
    statusLabel: string;
    statusPlaceholder: string;
    lastAccessLabel: string;
  };

  access: {
    systemTitle: string;
    systemDescription: string;
    credentialsTitle: string;
    credentialsDescription: string;
    loading: string;
    selectAuthority: string;
    selectCredential: string;
    add: string;
    remove: string;
    activate: string;
    deactivate: string;
    emptyAuthorities: string;
    emptyCredentials: string;
  };

  toast: {
    addSummary: string;
    addDetail: string;
    createdSummary: string;
    createdDetail: string;
    createErrorSummary: string;
    createErrorDetail: string;
    listErrorSummary: string;
    listErrorDetail: string;
    viewSummary: string;
    viewErrorSummary: string;
    viewErrorDetail: string;
    updatedSummary: string;
    updatedDetail: string;
    updateErrorSummary: string;
    updateErrorDetail: string;
    accessErrorSummary: string;
    accessErrorDetail: string;
    accessUpdatedSummary: string;
    accessUpdatedDetail: string;
    accessUpdateErrorSummary: string;
    accessUpdateErrorDetail: string;
    editSummary: string;
  };
}

export const userQueryTranslations: Record<AppLanguage, UserQueryTranslation> = {
  'en-US': {
    title: 'Users',
    subtitle: 'Manage access, roles and user status in the admin area.',
    addButton: 'Add user',

    stats: {
      total: 'Total users',
      active: 'Active users',
      pending: 'Pending users',
    },

    filters: {
      searchLabel: 'Search',
      searchPlaceholder: 'Search by name, email or role',
      statusLabel: 'Status',
      statusPlaceholder: 'Filter by status',
      allStatuses: 'All statuses',
    },

    statuses: {
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
    },

    table: {
      name: 'Name',
      email: 'Email',
      role: 'Role',
      status: 'Status',
      lastAccess: 'Last access',
      actions: 'Actions',
      loading: 'Loading users...',
      emptyTitle: 'No users found',
      emptyDescription: 'Try changing the filters or add a new user.',
      rowsPerPage: 'Rows per page',
      paginatorInfo: 'Showing {first}-{last} of {total}',
      firstPage: 'First page',
      previousPage: 'Previous page',
      nextPage: 'Next page',
      lastPage: 'Last page',
    },

    actions: {
      view: 'View',
      edit: 'Edit',
    },

    dialog: {
      addTitle: 'Add user',
      addSubtitle: 'Register the basic person information. The login will be generated by the API.',
      viewTitle: 'View user',
      viewSubtitle: 'User and person details returned by the API.',
      loadingView: 'Loading user...',
      close: 'Close dialog',
      closeButton: 'Close',
      cancel: 'Cancel',
      save: 'Save user',
      update: 'Update user',
    },

    form: {
      nameLabel: 'Person name',
      namePlaceholder: 'Enter the full name',
      emailLabel: 'Email',
      emailPlaceholder: 'Enter the email',
      phoneLabel: 'Phone',
      phonePlaceholder: 'Enter the phone',
      statusLabel: 'Status',
      statusPlaceholder: 'Select status',
      lastAccessLabel: 'Last access',
    },

    access: {
      systemTitle: 'Global permissions',
      systemDescription: 'System authorities linked directly to this user.',
      credentialsTitle: 'Credential access',
      credentialsDescription: 'Credentials and scoped authorities assigned to this user.',
      loading: 'Loading access...',
      selectAuthority: 'Select authority',
      selectCredential: 'Select credential',
      add: 'Add',
      remove: 'Remove',
      activate: 'Activate',
      deactivate: 'Deactivate',
      emptyAuthorities: 'No authorities linked.',
      emptyCredentials: 'No credentials linked.',
    },

    toast: {
      addSummary: 'New user',
      addDetail: 'The user creation flow will be connected in the next step.',
      createdSummary: 'User created',
      createdDetail: 'The user was created successfully.',
      createErrorSummary: 'Create user error',
      createErrorDetail: 'Unable to create the user. Check the fields and try again.',
      listErrorSummary: 'Load users error',
      listErrorDetail: 'Unable to load users. Try again in a moment.',
      viewSummary: 'View user',
      viewErrorSummary: 'View user error',
      viewErrorDetail: 'Unable to load the user details. Try again in a moment.',
      updatedSummary: 'User updated',
      updatedDetail: 'The user was updated successfully.',
      updateErrorSummary: 'Update user error',
      updateErrorDetail: 'Unable to update the user. Check the fields and try again.',
      accessErrorSummary: 'Load access error',
      accessErrorDetail: 'Unable to load access information. Try again in a moment.',
      accessUpdatedSummary: 'Access updated',
      accessUpdatedDetail: 'The access configuration was updated.',
      accessUpdateErrorSummary: 'Update access error',
      accessUpdateErrorDetail: 'Unable to update access. Try again in a moment.',
      editSummary: 'Edit user',
    },
  },

  'pt-BR': {
    title: 'Usuarios',
    subtitle: 'Gerencie acessos, perfis e status dos usuarios na area administrativa.',
    addButton: 'Adicionar usuario',

    stats: {
      total: 'Total de usuarios',
      active: 'Usuarios ativos',
      pending: 'Usuarios pendentes',
    },

    filters: {
      searchLabel: 'Busca',
      searchPlaceholder: 'Busque por nome, email ou perfil',
      statusLabel: 'Status',
      statusPlaceholder: 'Filtrar por status',
      allStatuses: 'Todos os status',
    },

    statuses: {
      active: 'Ativo',
      inactive: 'Inativo',
      pending: 'Pendente',
    },

    table: {
      name: 'Nome',
      email: 'Email',
      role: 'Perfil',
      status: 'Status',
      lastAccess: 'Ultimo acesso',
      actions: 'Acoes',
      loading: 'Carregando usuarios...',
      emptyTitle: 'Nenhum usuario encontrado',
      emptyDescription: 'Tente alterar os filtros ou adicione um novo usuario.',
      rowsPerPage: 'Linhas por pagina',
      paginatorInfo: 'Exibindo {first}-{last} de {total}',
      firstPage: 'Primeira pagina',
      previousPage: 'Pagina anterior',
      nextPage: 'Proxima pagina',
      lastPage: 'Ultima pagina',
    },

    actions: {
      view: 'Visualizar',
      edit: 'Editar',
    },

    dialog: {
      addTitle: 'Adicionar usuario',
      addSubtitle: 'Cadastre as informacoes basicas da pessoa. O login sera gerado pela API.',
      viewTitle: 'Visualizar usuario',
      viewSubtitle: 'Dados do usuario e da pessoa retornados pela API.',
      loadingView: 'Carregando usuario...',
      close: 'Fechar dialog',
      closeButton: 'Fechar',
      cancel: 'Cancelar',
      save: 'Salvar usuario',
      update: 'Atualizar usuario',
    },

    form: {
      nameLabel: 'Nome da pessoa',
      namePlaceholder: 'Digite o nome completo',
      emailLabel: 'Email',
      emailPlaceholder: 'Digite o email',
      phoneLabel: 'Telefone',
      phonePlaceholder: 'Digite o telefone',
      statusLabel: 'Status',
      statusPlaceholder: 'Selecione o status',
      lastAccessLabel: 'Ultimo acesso',
    },

    access: {
      systemTitle: 'Permissoes globais',
      systemDescription: 'Authorities de sistema vinculadas diretamente a este usuario.',
      credentialsTitle: 'Acesso a credenciais',
      credentialsDescription: 'Credenciais e authorities por escopo atribuidas a este usuario.',
      loading: 'Carregando acessos...',
      selectAuthority: 'Selecione a authority',
      selectCredential: 'Selecione a credencial',
      add: 'Adicionar',
      remove: 'Remover',
      activate: 'Ativar',
      deactivate: 'Desativar',
      emptyAuthorities: 'Nenhuma authority vinculada.',
      emptyCredentials: 'Nenhuma credencial vinculada.',
    },

    toast: {
      addSummary: 'Novo usuario',
      addDetail: 'O fluxo de criacao de usuario sera conectado na proxima etapa.',
      createdSummary: 'Usuario criado',
      createdDetail: 'O usuario foi criado com sucesso.',
      createErrorSummary: 'Erro ao criar usuario',
      createErrorDetail: 'Nao foi possivel criar o usuario. Verifique os campos e tente novamente.',
      listErrorSummary: 'Erro ao carregar usuarios',
      listErrorDetail: 'Nao foi possivel carregar os usuarios. Tente novamente em instantes.',
      viewSummary: 'Visualizar usuario',
      viewErrorSummary: 'Erro ao visualizar usuario',
      viewErrorDetail: 'Nao foi possivel carregar os detalhes do usuario. Tente novamente em instantes.',
      updatedSummary: 'Usuario atualizado',
      updatedDetail: 'O usuario foi atualizado com sucesso.',
      updateErrorSummary: 'Erro ao atualizar usuario',
      updateErrorDetail: 'Nao foi possivel atualizar o usuario. Verifique os campos e tente novamente.',
      accessErrorSummary: 'Erro ao carregar acessos',
      accessErrorDetail: 'Nao foi possivel carregar os acessos. Tente novamente em instantes.',
      accessUpdatedSummary: 'Acesso atualizado',
      accessUpdatedDetail: 'A configuracao de acesso foi atualizada.',
      accessUpdateErrorSummary: 'Erro ao atualizar acesso',
      accessUpdateErrorDetail: 'Nao foi possivel atualizar o acesso. Tente novamente em instantes.',
      editSummary: 'Editar usuario',
    },
  },
};
